### PR TITLE
chore: add vpc endpoints

### PR DESCRIPTION
**Pull request by ErdemAyyildiz**
*Issue #, if available:*

*VPC example should include the services that package communicates to enable private subnet. If not gen-ai-cdk-construct will create.*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by krokoko** [comment]
LGTM

**Comment by scottschreckengaust** [comment]
FYI: This needs to merge and be distributed first https://github.com/awslabs/generative-ai-cdk-constructs/pull/607

**Review by scottschreckengaust — CHANGES_REQUESTED** [review]
Wait for https://github.com/awslabs/generative-ai-cdk-constructs/pull/607

**Review by scottschreckengaust — APPROVED** [review]

**Comment by krokoko** [comment]
Reverting this since it is causing issues with the app (main changes to constructs were reverted)

**Pull request merged**
